name: CI

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:local
      volumes:
        - .:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Initial
        run: |
          composer install
      - name: Code Style
        run: |
          ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots
      - name: Test
        run: |
          ./vendor/bin/phpunit
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v2.0.0
        if: always()
        with:
          channel: CQPKN13E3
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
